### ISSUE TITLE
Discuss idiomatic changes

### ISSUE THREAD

**Issue by mike-barber** [mike-barber/daves-garage-primes#1]
Added this issue to discuss idiomatic changes to my solution with @Kulasko

**Comment by mike-barber** [comment]
Let's chat briefly about what we want to change, and then maybe create a branch to work on it. If you like, I'll add you as a contributor to this repo?

**Comment by Kulasko** [comment]
Thank for your consideration @mike-barber. I don't really think that's necessary, as we may discuss anything we want to change, anyway. Of course, if it would be more convenient for you, you can still add me.

As for how to do this, I'll just include everything I can think of right now as a starting point for further discussion.

- Small, purely cosmetic changes:
  - Every `<X>_BITS` constant can use `<x>::BITS as usize` instead of hard coded values. We can still use the constants because we still save on conversions in the code.
  - Every instance of creating all-true bit fields can use `<x>::MAX` instead of hard coded values.
  - The mask of the `get` method of `FlagStorageBitVectorStriped` has its shifted bit written as `1_u8`, this creates confusion (at least for me) on why the type is specified where it's not needed. This might be a matter of taste though.
  - There are some wild whitespaces around the file. I run of `cargo fmt` takes care of this.
  - I would like some more consistency on if there's a newline between a struct and its `impl` blocks.
  - The description of `FlagStorageBitVectorStriped` documented `U8_BITS` by mistake. Putting the constant somewhere else would be an idea to prevent such things, I would suggest the top of the module.
  - I like the documentation you've written so far. For the final state of the solution, I would like to have everything documented to have it clean and consistent. We can debate on whether this is the same as you would want.
  The following elements are still undocumented:
    - The U8_BITS and U32_BITS constants.
    - The functions in the crate root.
    - The crate itself and the `primes` module.
- Functionally equivalent changes:
  - As `known_results` of `PrimeValidator` is used exclusively by tests, using `#[cfg(test)]` instead of `#[allow(dead_code)]` would make the reason of its existence and its relation to the code clearer for the reader.
  - While determining the `run_all` variable in `main`, the iterator checks for a reference to be false. While the compiler seems to give it some leeway here, I would like to have either `.iter().copied().all(|b| !b)`, `.iter().all(|&b| !b)` or `.iter().all(|b| !*b)`.
  - The `known_results` method of `Primevalidator` exposes the entire content of the struct, which feels a bit weird. I would propose to make the method return an iterator instead of the content and adjust the test accordingly. This would also be an opportunity to show off `impl`returns as in `pub fn known_results_iter(&self) -> Impl Iterator<Item = (&usize, &usize)>`.
  - Clippy complains about using `eprint!("\n");` instead of `eprintln!();` in `print_results_stderr`.
  - I would like to move either the different `FlagStorage` elements or the whole `primes` module into a seperate file to improve readability on the main one.
- Potentially functional changes:
  - We can use `#[inline(always)]` annotation for the `get` methods of the `FlagStorage` trait. I think the compiler does this anyway, but it would make them more consistent with the `reset flags` methods which all have this annotation.
  - We can also use `#[inline(always)]` on the `is_num_flagged` method to make the intention more clear. I think, the compiler already inlines it anyways.
  - We could do the lookup of the next prime number with a step size of two instead of checking for an odd number in `is_num_flagged`. As more sophisticated iterators tend to not get optimized as much, this would need some though put into it. Some quick testing with `.step_by(2)` showed an improvement for a bit vector and a regression for the rotated bit vector on my machine.

This is everything that came to mind so far. Please let me know your thoughts on it and whether you disagree with some of the points. I expect us to eventually find a common perspective we can then implement.

I just realized that this is not briefly at all, I hope you don't mind too much.

**Comment by mike-barber** [comment]
Thanks @Kulasko and apologies for my slow response -- I had a really busy day at work. Always happens when you're planning a few days off :)

Thanks for the detailed code review. Most of this list is a really good idea, and we should do it. Some of it is stuff I was avoiding doing because I didn't want to make cosmetic changes at a late stage (like running Clippy). But Rutger seems happy with us doing so, so I think we're ok on that front. 

One thing I would avoid doing, though: moving things into different files, or move stuff around too much. While it's objectively better to do this, especially with multiple different FlagStorage implementations (I only had 2 originally), my thinking is that it's going to be a lot harder to review what we've changed with this PR. Git isn't great with this. There's been a fair bit of effort put in by the maintainers to review and ensure the code is "faithful", "base", etc. and it'll be easier for them to accept the PR we if it's very clear that it doesn't change anything that they'd be worried about. Moving stuff around will make that a bit harder, so I'm reluctant to do so. 

For the functional changes, I agree that the only one that will should have a performance impact is the next number search. I never gave it much attention because resetting bits was far the most expensive operation. If `step_by(2)` is better for the bit-storage cases, I think we should go ahead with it: it's the bit-storage variants that are the "main" competition, and it would be good for Rust to have a really good showing here ;) I'll just run a quick test on my hardware before we decide to merge -- I'm sure it'll be fine. 

In terms of how to to this, my suggestion is this: I'll add you as a contributor on this repo. This will allow us to open a PR here and discuss / check performance / etc, update docs, etc. Then we can merge that, and open a PR against the main repo. What do you think? 

Thanks again for going through this
Mike

**Comment by Kulasko** [comment]
No problem @mike-barber, we will still get it done, I'm sure of it ;)

Regarding moving code into another file. I do understand where you are coming from. I have to admit that I haven't been using git together with other people much so far. On the other hand, considering that we got asked to merge our single threaded solution and my solution already is in a separate file, don't you think the amount of work to review it is still reasonable if we do it cleanly, meaning in a dedicated commit?

For optimizing the prime number search, a while-loop would most likely run faster than an iterator with a step size. I discovered such an effect while building my solution already. An alternative would be to have the iterator iterator over the half values. However, when testing this, this results in the program crashing because of not finding the next prime number and I don't understand why. After removing halving the value from `is_num_flagged`,
`(factor..self.sieve_size).step_by(2).find(|n| self.is_num_flagged(*n / 2))`
works, but
`(factor..self.sieve_size).step_by(2).map(|n| n / 2).find(|n| self.is_num_flagged(*n))`
does not, nevermind the goal of
`(factor / 2..self.sieve_size / 2).find(|n| self.is_num_flagged(*n))`.
Surely I am missing something here.

It sounds like a good plan, so you can go ahead and add me. Except for moving code into another file and the prime search optimization, it seems we agree on if and how to do things.

**Comment by mike-barber** [comment]
I've added you as a collaborator on this repo, and created this branch that we can use as a **target** for PRs: https://github.com/mike-barber/daves-garage-primes/tree/rust-idiomatic-improvements

> Regarding moving code into another file. I do understand where you are coming from. I have to admit that I haven't been using git together with other people much so far. On the other hand, considering that we got asked to merge our single threaded solution and my solution already is in a separate file, don't you think the amount of work to review it is still reasonable if we do it cleanly, meaning in a dedicated commit?

Git gets pretty confusing when we move stuff around; it's a constant headache at work too. It might be worth experimenting with this _after_ we've done all the other stuff, on a separate branch. That way we'll still have all the other work in order if does turn out to be confusing. I know a few tricks with git that that might make it possible -- but we'll have to see. My two goals with this are to maintain the file history and ensure that the review process is still easy.

> For optimizing the prime number search, a while-loop would most likely run faster than an iterator with a step size. I discovered such an effect while building my solution already. An alternative would be to have the iterator iterator over the half values.

A while loop would definitely work better than the current approach. I'd avoid the iterator though: it's more complexity than we need. Let's look at this after the merging the idiomatic improvements into `rust-idiomatic-improvements` -- it'll allow us to validate performance on the idiomatic changes, then validate any additional improvements we make to the search separately.

> After removing halving the value from is_num_flagged,
> `(factor..self.sieve_size).step_by(2).find(|n| self.is_num_flagged(*n / 2))`
> works, but
> `(factor..self.sieve_size).step_by(2).map(|n| n / 2).find(|n| self.is_num_flagged(*n))`
> does not, nevermind the goal of
> `(factor / 2..self.sieve_size / 2).find(|n| self.is_num_flagged(*n)).`
> Surely I am missing something here.

That's a weird one. It could be subtle bug in there somewhere -- maybe push a separate branch with the offending code and I can take a look at it too :)

**Comment by mike-barber** [comment]
I ran `perf` earlier again to work out how much of the time we spend on finding the next prime, and it came out to 0.33% of the total for the single-threaded bit-storage case. 

It's a good number to keep in mind -- even doubling the performance of this part of the code won't yield a large performance boost. The `while` loop still sounds like a good idea though :)

**Comment by mike-barber** [comment]
@Kulasko I was playing around with the faster bit storage variants yesterday, and I had a bright idea that bumps the performance on a the striped bits variant from about 15500 to about 18000. I'm not sure whether I should open a PR to add it to this the `rust-idiomatic-improvements` branch, or whether I should do it later in a separate PR.

What else do we have left to do? I know you're keen to restructure the solution into separate files, and there might be a way to get `git` to co-operate. 

What would your ideal structure look like? 

It could be something simple like 
```
src/
  main.rs
  storage.rs
  sieve.rs
```

Or something a bit more fine-grained like
```
src/
  main.rs
  flag_storage.rs  <- trait
  flag_storage_bits.rs
  flag_storage_bits_rotate.rs
  flag_storage_bits_striped.rs
  flag_storage_bytes.rs
  sieve.rs
```

Let me know which you prefer, and I'll try creating a PR to see if git behaves.

**Comment by mike-barber** [comment]
I tried the simpler case above and opened a test PR: #6 -- it won't compile or anything; just checking to see what `git` does.

What I've found from this... I've been able to preserve the file history, so that's a small win at least. However, the PR itself is impossible to review for changes -- the files that were split off (storage, sieve) look like they're completely new, unfortunately.

I could maybe open a PR like this later, but I definitely wouldn't want to bundle the actual changes with splitting code into files.

**Comment by Kulasko** [comment]
As said multiple times already, thanks for your consideration :)

I normally take a pragmatic approach, where I move code into its own logic unit whenever it gets hard to find things when scrolling through. From this perspective, putting the prime module into its own file would be about as much as I would do.
Now, if we only want to restructure the project one time and also give it some breathing room for possible future expansions, a more fine-grained approach might be better.
I do have some thoughts:
```
src/
  sieve/
    flag_storage.rs
  sieve.rs
  benchmark.rs
  main.rs
```
This is how I might structure the current code. It might look weird to have only one file in a sub folder, but the folder primarily exists to make the relation between the modules clear.
`main.rs` would contain the main function, as well as the command line arguments. `benchmark.rs` would contain the `run_implementation` function and print functions. `sieve.rs` would contain the sieve, as well as the main documentation (if one wants to write one) and an import of `flag_storage.rs`, where the different storage type are. I'm not sure about the tests, as they are essentially testing the sieve, maybe they should reside in `sieve.rs`. Honestly, I would move the `PrimeValidator`into the test module, too, but you might be opposed to this change because it changes the structure from Dave's reference implementation pretty strongly.
I don't like many, small files too much, so I try to keep my file size between 50 and 250 lines most of the time.

Now if we would want to display "enterprise scaling", it might look like this:
```
src/
  sieve/
    algorithms/ <- maybe in the future
    flag_storage/
      bit_vector.rs
      bit_vector_rotate.rs
      bit_vector_striped.rs
      byte_vector.rs
    algorithms.rs <- maybe in the future
    flag_storage.rs <- trait
    test.rs
  sieve.rs
  benchmark.rs
  main.rs
```
This has more files, but scales pretty well and is clean.

Sad to hear that git doesn't seem to have a good way of splitting files. Well then, maybe we can do that later, if you are still willing to do so.

**Comment by mike-barber** [comment]
Thanks -- that makes a lot of sense. Given that I probably won't want to extend this solution too much further, the simpler folder structure would work best:

> ```
> src/
>   sieve/
>     flag_storage.rs
>   sieve.rs
>   benchmark.rs
>   main.rs
> ```

I'll see how Rutger feels about it when we submit the idiomatic PR, and open a second PR to do the above if he's happy with the idea.

**Comment by Kulasko** [comment]
This sounds like a good plan :)

**Comment by mike-barber** [comment]
I think we should leave the restructuring plan for now; we've got feedback on the PR: https://github.com/PlummersSoftwareLLC/Primes/pull/510

The good news is that everything else was merged successfully and it's now up to date and relatively polished. Thanks for all your input on this!

**Comment by Kulasko** [comment]
@mike-barber sounds good! A bit sad that we can't restructure, but as the repository exploded in the way that it has, it kind of is to be expected.
Also no problem, I want a good Rust solution as much as you :)

As for my solution, there's a bit of work to be done, but I might come around to it throughout the week.

**Comment by mike-barber** [comment]
Agreed -- it's a pity we can't restructure, but I think the project is in a reasonably good state now :)

Let me know if you'd like me to review anything when you're working on your solution.
